name: uQueue
main: me.noahvdaa.uqueue.BukkitPlugin
version: ${project.version}
author: NoahvdAa
api-version: 1.13
softdepend: [ PlaceHolderAPI ]
commands:
  queue:
    description: Forwards a queue request to the Bungee server.