#
#         ____
#        / __ \
#  _   _| |  | |_   _  ___ _   _  ___
# | | | | |  | | | | |/ _ \ | | |/ _ \
# | |_| | |__| | |_| |  __/ |_| |  __/
#  \__,_|\___\_\\__,_|\___|\__,_|\___|
#
# By NoahvdAa
#

Chat:
  # The prefix that is shown in front of every message.
  Prefix: "&8[&2u&aQueue&8]"
  # If this is enabled, /server will act the same as /queue.
  HijackServerCommand: false

Queueing:
  # The mode the server list below this setting should operate in.
  # Available options:
  #   - blacklist: Players that want to queue for servers in this list require the permission uqueue.server.<server>.
  #                All other servers can be queued for without any extra permissions.
  #   - whitelist: Players that want to queue for servers in this list don't require any extra permissions.
  #                All other servers can only be queued for if the player has the permission uqueue.server.<server>.
  ServerListMode: blacklist
  ServerList:
    - blacklistedserver
  # The amount of players to send to the server they're queued for, per second. Must be a non-decimal number.
  # This value can be overridden per-server in servers.yml.
  PlayersPerSecond: 1
  # The amount of seconds before a offline server is marked as "offline", rather than "restarting".
  # Set to 0 to effectively disable. This value can be overridden per-server in servers.yml.
  RestartLength: 30
  # The maximum amount of attempts to send someone to their target server before they're removed from queue.
  # Setting this too high may clog up your queue when someone isn't whitelisted, for example.
  # This value can be overridden per-server in servers.yml.
  MaxSendAttempts: 5
  # When this setting is enabled, the plugin will not ping servers that have no players in the queue.
  # This may prevent log-spam for server software not based on Spigot.
  # Queue servers are not affected by this!
  # Note: When this is enabled, the server has to be pinged first whenever a player joins the empty queue.
  #       Because of this, the queue may take a second longer to "get started" when this is enabled.
  #       This will also break the "RestartLength" setting.
  # This value can be overridden per-server in servers.yml.
  NoPingIfQueueEmpty: false
  # The server to send players to while queued. Players will not be sent to this server if it is offline or full.
  # It is recommended to use a server that uses a minimal amount of resources and can
  # hold large amount of players, like this one: https://www.spigotmc.org/resources/82468/
  # Set to an empty string to disable.
  # This value can be overridden per-server in servers.yml.
  QueueServer: ""

# DO NOT CHANGE THIS! THIS IS AUTOMATICALLY UPDATED BY THE PLUGIN
configVersion: 1