#
#         ____
#        / __ \
#  _   _| |  | |_   _  ___ _   _  ___
# | | | | |  | | | | |/ _ \ | | |/ _ \
# | |_| | |__| | |_| |  __/ |_| |  __/
#  \__,_|\___\_\\__,_|\___|\__,_|\___|
#
# By NoahvdAa
#

Chat:
  # The prefix that is shown in front of every message.
  Prefix: "&8[&2u&aQueue&8]"

Queueing:
  # The mode the server list below this setting should operate in.
  # Available options:
  #   - blacklist: Players that want to queue for servers in this list require the permission uqueue.server.<server>.
  #                All other servers can be queued for without any extra permissions.
  #   - whitelist: Players that want to queue for servers in this list don't require any extra permissions.
  #                All other servers can only be queued for if the player has the permission uqueue.server.<server>.
  ServerListMode: blacklist
  ServerList:
    - blacklistedserver
  # The amount of players to send to the server they're queued for, per second.
  PlayersPerSecond: 1
  # The amount of seconds before a offline server is marked as "offline", rather than "restarting".
  # Set to 0 to effectively disable
  RestartLength: 30
  # The maximum amount of attempts to send someone to their target server before they're removed from queue.
  # Setting this too high may clog up your queue when someone isn't whitelisted, for example.
  MaxSendAttempts: 5


# DO NOT CHANGE THIS! THIS IS AUTOMATICALLY UPDATED BY THE PLUGIN
configVersion: 1